(() => {'use strict';
const $=id=>document.getElementById(id), val=id=>$(id).value.trim(), number=id=>val(id)===''?NaN:Number(val(id).replace(',','.'));
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=(x,d=2)=>Number.isFinite(x)?x.toLocaleString('ru-RU',{minimumFractionDigits:d,maximumFractionDigits:d}):'—';
let latest=null;
function buildSections(){ $('sections').innerHTML=[1,2,3].map(i=>`<label>Сечение ${i}: d / a, мм<input id="a${i}" type="number" min="0" step="any"></label><label>Сечение ${i}: b, мм <span class="muted">(только плоский)</span><input id="b${i}" type="number" min="0" step="any"></label>`).join(''); }
function geometryHint(){try{const sections=[1,2,3].map(i=>({a:number('a'+i),b:number('b'+i)})); const g=GOST1497.geometry(val('shape'),sections); const factor={short:5.65,long:11.3,brittle:2.82}[val('lengthType')]; const step=val('lengthType')==='short'?5:val('lengthType')==='long'?10:null; $('geometryHint').textContent=`F₀ = ${fmt(g.f0)} мм² (минимальное сечение); средняя площадь для E = ${fmt(g.fE)} мм². ${factor?`Расчётная длина ${fmt(factor*Math.sqrt(g.f0))} мм${step?`; округление вверх до ${step} мм: ${Math.ceil(factor*Math.sqrt(g.f0)/step)*step} мм`:''}. Измеренную l₀ внесите отдельно.`:''}`;}catch{$('geometryHint').textContent='Введите размеры всех трёх сечений.';}}
function parseRows(text){const rows=[];for(const [i,line] of text.split(/\r?\n/).entries()){if(!line.trim())continue;let parts=line.includes(';')?line.split(';'):line.includes('\t')?line.split('\t'):line.split(',');parts=parts.map(x=>x.trim().replace(',','.'));const a=Number(parts[0]),b=Number(parts[1]);if(!Number.isFinite(a)||!Number.isFinite(b)){if(rows.length===0&&i===0)continue;throw Error(`Строка ${i+1}: ожидаются числа в первых двух столбцах.`);}const t=parts[2]?.trim();rows.push({deformation:a,force:b,time:t==null||t===''?null:Number(t)});if(t!=null&&t!==''&&!Number.isFinite(Number(t)))throw Error(`Строка ${i+1}: некорректное время.`);}return rows;}
function draw(data){const c=$('plot'),ctx=c.getContext('2d'),w=c.width,h=c.height;ctx.clearRect(0,0,w,h);let maxX=Math.max(...data.map(p=>p.x)),maxY=Math.max(...data.map(p=>p.y));if(!(maxX>0&&maxY>0))return;c.hidden=false;ctx.strokeStyle='#bdc8d4';ctx.beginPath();ctx.moveTo(55,15);ctx.lineTo(55,h-40);ctx.lineTo(w-15,h-40);ctx.stroke();ctx.fillStyle='#354960';ctx.font='14px sans-serif';ctx.fillText('σ, МПа',8,24);ctx.fillText('ε, %',w-65,h-12);ctx.fillText(fmt(maxY,0),9,43);ctx.fillText(fmt(maxX*100,1),w-65,h-48);ctx.strokeStyle='#147d90';ctx.lineWidth=2;ctx.beginPath();data.forEach((p,i)=>{let x=55+p.x/maxX*(w-75),y=h-40-p.y/maxY*(h-60);i?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.stroke();}
function row(name,value){return `<tr><th>${name}</th><td>${value}</td></tr>`;}
function analyze(){try{const sections=[1,2,3].map(i=>({a:number('a'+i),b:number('b'+i)}));const source=val('strainSource');const result=GOST1497.analyze({shape:val('shape'),sections,l0:number('l0'),lk:number('lk'),neck:{a:number('neckA'),b:number('neckB')},breakPosition:val('breakPosition'),forceData:parseRows(val('raw')),strainSource:source==='mm'?'mm':source,gaugeBase:number('gaugeBase'),fitMin:number('fitMin'),fitMax:number('fitMax'),timeUnit:val('timeUnit')});latest=result;const symbol={short:'δ₅',long:'δ₁₀',brittle:'δ (2,82)',other:'δ (l₀ указана)'}[val('lengthType')];let items=[['F₀, мм²',fmt(result.g.f0,GOST1497.areaStep(result.g.f0)<1?2:0)],['Pmax, Н',fmt(result.pmax,0)],['σв, МПа',fmt(GOST1497.roundTo(result.sigmaB,1),0)],['E, ГПа',result.e?fmt(GOST1497.roundTo(result.e.slope/1000,.1),1):'не определён'],['σ₀.₂, МПа',result.offset?fmt(GOST1497.roundTo(result.offset.stress,1),0):'не определён'],[symbol+', %',result.delta!=null?fmt(GOST1497.roundTo(result.delta,result.delta<=10?.1:.5),result.delta<=10?1:1):'не определено'],['ψ, %',result.psi!=null?fmt(GOST1497.roundTo(result.psi,1),0):'не определено']];$('output').innerHTML=`<section class="result"><h2>Результаты</h2><table>${items.map(a=>row(...a)).join('')}</table><p>Кандидат σтв / σтн: ${result.phys?`${fmt(result.phys.upper,0)} / ${fmt(result.phys.lower,0)} МПа. Требуется разметка и подтверждение оператором.`:'не обнаружен; значения не выдаются.'}</p><p>Регрессия E: ${result.e?`${result.e.n} точек; r² = ${fmt(result.e.r2,6)}`:'не выполнена'}.</p><p>Скорость на выбранном участке: ${result.speed?`dε/dt = ${result.speed.strainRate.toExponential(3)} с⁻¹; dσ/dt = ${fmt(result.speed.stressRate,3)} МПа/с (${result.speed.points} точек)`:'не оценена'}. Соответствие методу А/Б подтверждается оператором по полной записи и условиям испытания.</p>${result.warnings.length?`<div class="notice"><strong>Проверить:</strong><ul>${result.warnings.map(w=>`<li>${esc(w)}</li>`).join('')}</ul></div>`:''}</section>`;draw(result.data);
const fields=[['Номер',val('protocolNo')],['Дата',val('date')],['Материал',val('material')],['Плавка',val('heat')],['Образец',val('sample')],['НД на продукцию',val('productStandard')],['Направление отбора',val('direction')],['Форма / исполнение',`${val('shape')==='round'?'цилиндрический':'плоский'}; ${val('type')}`],['Машина',val('machine')],['Экстензометр',val('extensometer')],['Температура, °C',val('temperature')],['Метод / заданная скорость',`${val('method')||'не указан'}; ${val('setSpeed')||'не указана'}`],['Оператор',val('operator')],['Неопределённость E',val('uncertainty')],['Размеры, мм',sections.map((s,i)=>`№${i+1}: ${s.a}${val('shape')==='flat'?' × '+s.b:''}`).join('; ')],['l₀ / lк, мм',`${val('l0')} / ${val('lk')||'—'}`],['Размеры после разрыва, мм',`${val('neckA')||'—'} × ${val('neckB')||'—'}`],['Положение разрыва',val('breakPosition')],['Интервал регрессии, МПа',`${val('fitMin')||'—'}–${val('fitMax')||'—'}`],['Число точек / r²',result.e?`${result.e.n} / ${fmt(result.e.r2,6)}`:'не определены']];$('protocol').hidden=false;$('protocol').innerHTML=`<h2>Расчётный лист испытания на растяжение</h2><p>ГОСТ 1497-2023 · Проект протокола; результаты требуют проверки и утверждения лабораторией.</p><table>${fields.map(([k,v])=>row(esc(k),esc(v||'не указано'))).join('')}</table><h3>Результаты</h3><table>${items.map(a=>row(...a)).join('')}</table><p>σтв/σтн: ${result.phys?'кандидаты не подтверждены':'не определены'}. Скорость: ${result.speed?`${result.speed.strainRate.toExponential(3)} с⁻¹ / ${fmt(result.speed.stressRate,3)} МПа/с`:'нет измеренных данных'}.</p><p>Замечания: ${esc(result.warnings.join(' '))}</p>`;$('print').hidden=$('save').hidden=false;
}catch(e){latest=null;$('output').innerHTML=`<div class="notice">${esc(e.message)}</div>`;$('protocol').hidden=$('print').hidden=$('save').hidden=true;$('plot').hidden=true;}}
buildSections();$('date').value=new Date().toISOString().slice(0,10);$('shape').addEventListener('change',geometryHint);$('lengthType').addEventListener('change',geometryHint);$('sections').addEventListener('input',geometryHint);$('file').addEventListener('change',async e=>{const f=e.target.files[0];if(f)$('raw').value=await f.text();});$('analyze').addEventListener('click',analyze);$('print').addEventListener('click',()=>window.print());$('save').addEventListener('click',async()=>{if(!latest)return;try{await openDB();const tx=db.transaction(STORE_NAME,'readwrite');tx.objectStore(STORE_NAME).add({date:new Date().toISOString(),protocol:$('protocol').innerHTML});tx.oncomplete=()=>alert('Сохранено в архиве этого браузера');tx.onerror=()=>alert('Не удалось сохранить');}catch(e){alert('Не удалось сохранить: '+e.message);}});
})();
